### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-1-infografia-Ariadnamonserrat10#1]
*Ariadna Monserrat López Aparicio

![Ciclo de vida del software](https://github.com/user-attachments/assets/2cb832d2-3de8-4012-9e0d-dadc01a10b4e)

**Comment by SandyMarissaGs** [comment]
De acuerdo a la rúbrica obtuviste el 20%

**Comment by josealfredo79** [comment]
bien hecho y revisado..
